spring:
  application:
    name: uploader

#server:
#  port: 7001


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #EUREKA_URL=//<container-name>:<port>
      defaultZone: http:${EUREKA_URL://13.48.248.158:5555/}/eureka/

      #defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://13.48.248.158:5555/eureka/
  instance:
    hostname: localhost

